server:
  port: 8080

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpassword
      database: escolalura
      port: 27019
      host: 127.0.0.1
